export const POPULAR_LOCATIONS = [
    { value: "mumbai", label: "Mumbai, Maharashtra" },
    { value: "delhi", label: "New Delhi, Delhi" },
    { value: "goa", label: "Goa, India" },
    { value: "bangalore", label: "Bangalore, Karnataka" },
    { value: "jaipur", label: "Jaipur, Rajasthan" },
    { value: "udaipur", label: "Udaipur, Rajasthan" },
    { value: "chennai", label: "Chennai, Tamil Nadu" },
    { value: "hyderabad", label: "Hyderabad, Telangana" },
    { value: "kolkata", label: "Kolkata, West Bengal" },
    { value: "pune", label: "Pune, Maharashtra" },
    { value: "kochi", label: "Kochi, Kerala" },
    { value: "agra", label: "Agra, Uttar Pradesh" },
    { value: "varanasi", label: "Varanasi, Uttar Pradesh" },
    { value: "rishikesh", label: "Rishikesh, Uttarakhand" },
    { value: "manali", label: "Manali, Himachal Pradesh" },
    { value: "shimla", label: "Shimla, Himachal Pradesh" },
    { value: "jodhpur", label: "Jodhpur, Rajasthan" },
    { value: "amritsar", label: "Amritsar, Punjab" },
];
